### ISSUE TITLE
Error when trying install under node 5.0.0 stable

### ISSUE THREAD

**Issue by luizfilipe** [electron-archive/node-chromium-pickle#5]
The problem is ocurring when I've run the command `npm install chromium-pickle`

I've got also the same problem under 4.2.1

``` sh
> chromium-pickle@0.1.4 install /Users/my_user/Documents/workspace/former/node_modules/chromium-pickle
> node-gyp rebuild

  CXX(target) Release/obj.target/native_mate/../native-mate/vendor/src/native_mate/arguments.o
In file included from ../../native-mate/vendor/src/native_mate/arguments.cc:5:
In file included from ../../native-mate/vendor/src/native_mate/arguments.h:10:
In file included from ../../native-mate/vendor/src/native_mate/converter.h:13:
../../native-mate/header_redirect/v8/include/v8.h:2:10: fatal error: '../deps/v8/include/v8.h' file not found
#include "../deps/v8/include/v8.h"
         ^
1 error generated.
make: *** [Release/obj.target/native_mate/../native-mate/vendor/src/native_mate/arguments.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/my_user/.nvm/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/my_user/.nvm/v5.0.0/bin/node" "/Users/my_user/.nvm/v5.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/my_user/Documents/workspace/former/node_modules/chromium-pickle
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPACKAGEJSON boilerplate@2.1.3 No repository field.
npm WARN EPACKAGEJSON boilerplate@2.1.3 No license field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/my_user/.nvm/v5.0.0/bin/node" "/Users/my_user/.nvm/v5.0.0/bin/npm" "install" "chromium-pickle"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! chromium-pickle@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromium-pickle@0.1.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the chromium-pickle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromium-pickle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/my_user/Documents/workspace/former/npm-debug.log
```

**Comment by kevinsawicki** [comment]
Is this error different than #4?
